server.document-root = "/tmp/www"

server.max-request-size = 65536

#server.use-ipv6 = "enable"

server.port = 8081
server.tag = ""
server.errorlog = "/tmp/lighttpd.error.log"

server.modules = (
    "mod_rewrite",
    "mod_access",
    "mod_auth",
    "mod_redirect",
    "mod_proxy",
    "mod_openssl",
)

server.indexfiles = (
    "index.php",
    "index.html",
    "index.htm",
    "default.htm",
)

$SERVER["socket"] == ":8082" {
    ssl.engine = "enable"
    ssl.pemfile = "/boaroot/lighttpd.pem"
	ssl.openssl.ssl-conf-cmd = ("MaxProtocol" => "TLSv1.2")

    proxy.server = (
        "" => (
            (
                "host" => "127.0.0.1",
                "port" => 8080
            )
        )
    )
}

proxy.server = (
    "" => (
        (
            "host" => "127.0.0.1",
            "port" => 8080
        )
    )
)
