ssl.pemfile = "/boaroot/lighttpd.pem"
ssl.openssl.ssl-conf-cmd = ("MaxProtocol" => "TLSv1.2")

$SERVER["socket"] == "[::]:443" {
    server.use-ipv6 = "enable"
    ssl.engine = "enable"
    proxy.server = (
        "" => (
            (
                "host" => "127.0.0.1",
                "port" => 8080
            )
        )
    )
}

$SERVER["socket"] == ":<%httpsPort%>" {
    ssl.engine = "enable"
    proxy.server = (
        "" => (
            (
                "host" => "127.0.0.1",
                "port" => 8080
            )
        )
    )
}

$HTTP["scheme"] == "http" {
    $HTTP["host"] =~ "^[^:]*" {
        url.redirect = (".*" => "https://%0:<%httpsPort%>$0")
    }
}

