server.document-root = "/tmp/www"

server.max-request-size = 65536

#server.use-ipv6 = "enable"

server.port = 80
server.tag = ""
server.errorlog = "/tmp/lighttpd.error.log"

server.modules = (
    "mod_rewrite",
    "mod_access",
    "mod_auth",
    "mod_redirect",
    "mod_proxy",
    "mod_openssl",
)

server.indexfiles = (
    "index.php",
    "index.html",
    "index.htm",
    "default.htm",
)

include_shell "if [ -f /tmp/lighttpd_ssl.conf ]; then cat /tmp/lighttpd_ssl.conf; fi"

