MqttBrokerHost = 0
MqttBrokerPort = 0
MqttUsername = 0
MqttPassword = 0
DeviceVendor = vG-421WD-v2
DeviceSerial = VTGR9153a1c0
MqttQoS = 1
MqttTls = 1
MqttCAFile = /data/vcs/mqtt-ca.crt
MqttTopicEncryption = 2
MqttLogLevel = 0
MqttEnable = 0
VCSAgentEnable = 0
MqttTlsInsecure = 1
MqttAuthorMethod = 1
MqttToken = 0
ApiPublicKey = /data/vcs/public_key.pem
ApiToken = 0
ApiDomain = mysafe.vietteltelecom.vn
ApiLogin = /staging/ont/api/v1/login
ApiBroker = /staging/ont/api/v1/brokers
ApiPort = 443
ApiTls = 1