[options]
	logfile = /var/log/knockd.log
[openSection]
	sequence    = 7000,8000,9000
	seq_timeout = 10
	tcpflags    = syn
	command     = /userfs/bin/tcapi set customerdebug_ssh Enable Yes && /userfs/bin/tcapi commit customerdebug_ssh > /dev/null 2>&1
[closeSection]
	sequence    = 9000,8000,7000
	seq_timeout = 10
	tcpflags    = syn
	command     = /userfs/bin/tcapi set customerdebug_ssh Enable No && /userfs/bin/tcapi commit customerdebug_ssh > /dev/null 2>&1